"""Procurement-related schema models.

Request and response schemas for the procurement analysis workflow.
"""

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field

from app.api.v1.schemas.common import BaseResponse


# ============================================================================
# Request Models
# ============================================================================


class ProcurementRequest(BaseModel):
    """Main procurement request from frontend.
    
    Represents a user's procurement need in natural language.
    The backend will normalize, extract, and analyze this request.
    """

    title: str = Field(
        ...,
        min_length=3,
        max_length=200,
        description="Brief title of the procurement need",
        example="Server purchase for data center upgrade",
    )

    description: str = Field(
        ...,
        min_length=10,
        max_length=5000,
        description="Detailed description of the procurement need",
        example="We need to purchase high-performance servers for our expanding data center...",
    )

    category: Literal[
        "IT_HARDWARE",
        "IT_SOFTWARE",
        "OFFICE_SUPPLIES",
        "SERVICES",
        "CONSTRUCTION",
        "EQUIPMENT",
        "CONSULTING",
        "OTHER",
    ] = Field(
        ...,
        description="Procurement category",
        example="IT_HARDWARE",
    )

    budget: Optional[float] = Field(
        None,
        gt=0,
        description="Budget in USD",
        example=500000.0,
    )

    urgency: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        "MEDIUM",
        description="Urgency level",
        example="HIGH",
    )

    department: Optional[str] = Field(
        None,
        max_length=100,
        description="Requesting department",
        example="Infrastructure Team",
    )

    preferred_supplier: Optional[str] = Field(
        None,
        max_length=200,
        description="Preferred supplier (optional)",
        example="Dell",
    )

    class Config:
        """Pydantic config."""
        json_schema_extra = {
            "example": {
                "title": "Server purchase for data center upgrade",
                "description": "We need to purchase 10 high-performance servers with redundant power supplies...",
                "category": "IT_HARDWARE",
                "budget": 500000.0,
                "urgency": "HIGH",
                "department": "Infrastructure",
                "preferred_supplier": "Dell",
            }
        }


# ============================================================================
# Internal Models (used by workflow)
# ============================================================================


class NormalizedRequest(BaseModel):
    """Normalized version of procurement request.
    
    Generated by the normalize_request_node.
    """

    original_title: str
    original_description: str
    normalized_title: str
    normalized_description: str
    category: str
    budget_amount: Optional[float]
    budget_currency: str = "USD"
    urgency_level: str
    department: Optional[str]
    preferred_supplier: Optional[str]


class Requirement(BaseModel):
    """Extracted procurement requirement."""

    id: str = Field(..., description="Unique requirement ID")
    name: str = Field(..., description="Requirement name")
    description: str = Field(..., description="Detailed description")
    priority: Literal["MUST_HAVE", "SHOULD_HAVE", "NICE_TO_HAVE"] = Field(
        ..., description="Priority level"
    )
    type: str = Field(..., description="Type: technical, business, compliance, etc.")


class PolicyChunk(BaseModel):
    """Policy document chunk retrieved from ChromaDB."""

    id: str = Field(..., description="Unique chunk ID")
    content: str = Field(..., description="Policy text")
    source: str = Field(..., description="Policy source document")
    section: Optional[str] = Field(None, description="Document section")
    similarity_score: float = Field(..., ge=0, le=1, description="Similarity score")
    metadata: dict = Field(default_factory=dict, description="Additional metadata")


class RiskFlag(BaseModel):
    """Identified risk or policy mismatch."""

    id: str = Field(..., description="Unique risk ID")
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        ..., description="Risk severity"
    )
    category: str = Field(..., description="Risk category")
    description: str = Field(..., description="Risk description")
    policy_reference: Optional[str] = Field(None, description="Relevant policy")
    mitigation: Optional[str] = Field(None, description="Suggested mitigation")


class RecommendationItem(BaseModel):
    """Recommended next step or action."""

    id: str = Field(..., description="Unique recommendation ID")
    action: str = Field(..., description="Recommended action")
    description: str = Field(..., description="Action description")
    priority: Literal["P1", "P2", "P3"] = Field(..., description="Priority")
    owner: Optional[str] = Field(None, description="Responsible party")
    timeline: Optional[str] = Field(None, description="Timeline for action")


# ============================================================================
# Response Models
# ============================================================================


class AnalysisResponse(BaseResponse):
    """Complete procurement analysis response.
    
    Returned by /api/v1/procurement/analyze endpoint.
    """

    summary: str = Field(
        ...,
        description="Executive summary of the analysis",
        example="Analysis recommends approval with conditions...",
    )

    normalized_request: NormalizedRequest = Field(
        ..., description="Normalized interpretation of the request"
    )

    extracted_requirements: list[Requirement] = Field(
        default_factory=list,
        description="Extracted structured requirements",
    )

    policy_snippets: list[PolicyChunk] = Field(
        default_factory=list,
        description="Relevant policy documents retrieved",
    )

    risk_flags: list[RiskFlag] = Field(
        default_factory=list,
        description="Identified risks and policy mismatches",
    )

    confidence_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Confidence in the analysis (0-1)",
        example=0.85,
    )

    confidence_label: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        ...,
        description="Confidence level label (LOW < 0.5, MEDIUM 0.5-0.75, HIGH > 0.75)",
        example="HIGH",
    )

    confidence_reason: str = Field(
        ...,
        description="Explanation of confidence score",
        example="Good policy context retrieved, complete requirements extracted",
    )

    recommendation_items: list[RecommendationItem] = Field(
        default_factory=list,
        description="Recommended next steps",
    )

    recommendation_summary: str = Field(
        ...,
        description="Summary of recommended actions",
        example="Proceed with procurement from approved supplier...",
    )

    processing_time_ms: float = Field(
        ...,
        ge=0,
        description="Total processing time in milliseconds",
        example=2345.5,
    )

    class Config:
        """Pydantic config."""
        json_schema_extra = {
            "example": {
                "request_id": "req-123",
                "trace_id": "trace-456",
                "timestamp": "2024-01-15T10:30:00Z",
                "summary": "Server procurement request approved...",
                "normalized_request": {
                    "original_title": "Server purchase",
                    "normalized_title": "Purchase of High-Performance Servers",
                    "category": "IT_HARDWARE",
                    "budget_amount": 500000,
                },
                "extracted_requirements": [
                    {
                        "id": "req-1",
                        "name": "Processing Power",
                        "description": "Minimum 48 cores per server",
                        "priority": "MUST_HAVE",
                        "type": "technical",
                    }
                ],
                "policy_snippets": [
                    {
                        "id": "policy-1",
                        "content": "All hardware purchases must be from approved vendors...",
                        "source": "IT Hardware Policy",
                        "similarity_score": 0.92,
                    }
                ],
                "risk_flags": [
                    {
                        "id": "risk-1",
                        "severity": "MEDIUM",
                        "category": "SUPPLIER",
                        "description": "Supplier not on approved list",
                        "mitigation": "Add supplier to approved list",
                    }
                ],
                "confidence_score": 0.88,
                "recommendation_items": [
                    {
                        "id": "rec-1",
                        "action": "Get supplier approval",
                        "description": "Submit Dell for supplier approval",
                        "priority": "P1",
                        "timeline": "1 week",
                    }
                ],
                "recommendation_summary": "Proceed after supplier approval",
                "processing_time_ms": 2345.5,
            }
        }


# ============================================================================
# Request History Models
# ============================================================================


class ProcurementRequestSummary(BaseModel):
    """Summary view of a submitted procurement request."""

    id: int
    title: str
    category: str
    budget: Optional[float]
    urgency: str
    department: Optional[str]
    created_at: datetime
    status: Literal["SUBMITTED", "ANALYZED"]


class ProcurementRequestDetail(BaseModel):
    """Detailed view of a submitted procurement request."""

    id: int
    title: str
    description: str
    category: str
    budget: Optional[float]
    urgency: str
    department: Optional[str]
    preferred_supplier: Optional[str]
    created_at: datetime
    status: Literal["SUBMITTED", "ANALYZED"]
    latest_analysis: Optional[AnalysisResponse] = None


class QuickHealthResponse(BaseModel):
    """Quick health/readiness response."""

    status: str = Field(..., description="Status: ok, degraded, unavailable")
    message: str = Field(..., description="Status message")
