"""Add Vendor model

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-04

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=False),
    sa.Column('cin_number', sa.String(length=21), nullable=True),
    sa.Column('msme_registered', sa.Boolean(), nullable=False),
    sa.Column('udyam_number', sa.String(length=20), nullable=True),
    sa.Column('msme_type', sa.String(length=20), nullable=True, comment='MICRO, SMALL, MEDIUM'),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('compliance_status', sa.String(length=20), nullable=False, comment='PENDING, VERIFIED, REJECTED'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin_number'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('udyam_number')
    )
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=True)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_legal_name'), 'vendors', ['legal_name'], unique=False)
    op.create_index(op.f('ix_vendors_pan_number'), 'vendors', ['pan_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_pan_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_legal_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
